# Use postgres/example user/password credentials
version: '3.1'

services:
  flask:
    build: app-backend
    depends_on:
      - db
    env_file:
        - .env
    environment:
      HOST_IP: ${HOST_IP}
      HOST_PORT: ${HOST_PORT}
    ports:
      - 5000:5000

  db:
      image: postgres:13.3-alpine
      restart: always
      env_file:
       - .env
      volumes:
        - db_data:/var/lib/postgresql/data
        - ./db:/docker-entrypoint-initdb.d
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080

volumes:
  db_data: